### ISSUE TITLE
Update from Origin to EA App

### ISSUE THREAD

**Issue by aleDsz** [cetteup/joinme.click-launcher#58]
Since we aren't using Origin App anymore, this tool should update to start using the EA App.

![image](https://user-images.githubusercontent.com/6402997/236585275-58b047ac-1eea-4d5d-a0d9-c539ee324de7.png)

**Comment by cetteup** [comment]
Switching to the EA app does not make much sense at the moment, as it does not support the required features.

You can get it to launch the game similar to how Origin did, but it does not join the server. The EA app does not pass the server-related arguments to the game, hence you just end up in the main menu. @the-eduardo also noted this in #59.

I prefer to keep the Origin-related code (which theoretically still works), rather than switch to the EA app without it providing the relevant features.

Once the EA app offers a reliable way to launch the game **and** join the server, I'll release an update. Otherwise the only way forward is to remove support for BF4 and BF1.

**Comment by aleDsz** [comment]
Thanks for the answer, it makes sense, since me and @the-eduardo tried to fix this issue.

**Comment by zefanjajobse** [comment]
#63 should fix this, tested bf1 ea desktop, bf1 steam and bf4 ea desktop
